#### Dataset and Dataloader torch

In [1]:
import torch 
import numpy as np
import math 
from torch.utils.data import Dataset,DataLoader


In [2]:
wine_path="D:\\machine learning\\torch_learnings\\data\\wine.csv"

In [3]:
class WineData(Dataset):

    def __init__(self,path):
        ## to read data 
        self.data=np.loadtxt(path,delimiter=',',dtype=np.float32,skiprows=1)
        self.x=torch.tensor(self.data[:,1:])
        self.y=torch.tensor(self.data[:,0])
        self.samples=self.x.shape[0]
        self.features=self.x.shape[1]

    
    def __getitem__(self,index):
        ## to get the object at the index present 
        return self.x[index],self.y[index]
    def __len__(self):
        return self.samples

In [4]:
wine_data=WineData(wine_path)

In [5]:
first_data=wine_data[0]

In [6]:
first_data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor(1.))

In [7]:
input1,output1=first_data

In [8]:
print(input1,"\n",output1)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) 
 tensor(1.)


In [9]:
wine_data.samples

178

### dataloader

In [10]:
wine_data=WineData(wine_path)

In [11]:
n_samples=wine_data.samples

In [12]:
data=DataLoader(dataset=wine_data,batch_size=5,shuffle=True)

In [20]:
len(data)

36

In [14]:
data.batch_size

5

In [23]:
data

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor(1.))

In [15]:
dataiter=iter(data)

In [16]:
first_data=next(dataiter)

In [17]:
first_data

[tensor([[1.3490e+01, 1.6600e+00, 2.2400e+00, 2.4000e+01, 8.7000e+01, 1.8800e+00,
          1.8400e+00, 2.7000e-01, 1.0300e+00, 3.7400e+00, 9.8000e-01, 2.7800e+00,
          4.7200e+02],
         [1.3870e+01, 1.9000e+00, 2.8000e+00, 1.9400e+01, 1.0700e+02, 2.9500e+00,
          2.9700e+00, 3.7000e-01, 1.7600e+00, 4.5000e+00, 1.2500e+00, 3.4000e+00,
          9.1500e+02],
         [1.4060e+01, 2.1500e+00, 2.6100e+00, 1.7600e+01, 1.2100e+02, 2.6000e+00,
          2.5100e+00, 3.1000e-01, 1.2500e+00, 5.0500e+00, 1.0600e+00, 3.5800e+00,
          1.2950e+03],
         [1.1840e+01, 2.8900e+00, 2.2300e+00, 1.8000e+01, 1.1200e+02, 1.7200e+00,
          1.3200e+00, 4.3000e-01, 9.5000e-01, 2.6500e+00, 9.6000e-01, 2.5200e+00,
          5.0000e+02],
         [1.2160e+01, 1.6100e+00, 2.3100e+00, 2.2800e+01, 9.0000e+01, 1.7800e+00,
          1.6900e+00, 4.3000e-01, 1.5600e+00, 2.4500e+00, 1.3300e+00, 2.2600e+00,
          4.9500e+02]]),
 tensor([2., 1., 1., 2., 2.])]

In [18]:
second_data=next(dataloader)

In [19]:
second_data

[tensor([[1.3270e+01, 4.2800e+00, 2.2600e+00, 2.0000e+01, 1.2000e+02, 1.5900e+00,
          6.9000e-01, 4.3000e-01, 1.3500e+00, 1.0200e+01, 5.9000e-01, 1.5600e+00,
          8.3500e+02],
         [1.3280e+01, 1.6400e+00, 2.8400e+00, 1.5500e+01, 1.1000e+02, 2.6000e+00,
          2.6800e+00, 3.4000e-01, 1.3600e+00, 4.6000e+00, 1.0900e+00, 2.7800e+00,
          8.8000e+02],
         [1.2420e+01, 1.6100e+00, 2.1900e+00, 2.2500e+01, 1.0800e+02, 2.0000e+00,
          2.0900e+00, 3.4000e-01, 1.6100e+00, 2.0600e+00, 1.0600e+00, 2.9600e+00,
          3.4500e+02],
         [1.4390e+01, 1.8700e+00, 2.4500e+00, 1.4600e+01, 9.6000e+01, 2.5000e+00,
          2.5200e+00, 3.0000e-01, 1.9800e+00, 5.2500e+00, 1.0200e+00, 3.5800e+00,
          1.2900e+03],
         [1.4160e+01, 2.5100e+00, 2.4800e+00, 2.0000e+01, 9.1000e+01, 1.6800e+00,
          7.0000e-01, 4.4000e-01, 1.2400e+00, 9.7000e+00, 6.2000e-01, 1.7100e+00,
          6.6000e+02]]),
 tensor([3., 1., 2., 1., 3.])]

### enumerate and for models 

In [24]:
final_data=DataLoader(dataset=wine_data,batch_size=5,shuffle=True)

In [32]:
for i,(inp,out) in enumerate(final_data):
    print(f"{i} : {inp} : {out}")

0 : tensor([[1.3410e+01, 3.8400e+00, 2.1200e+00, 1.8800e+01, 9.0000e+01, 2.4500e+00,
         2.6800e+00, 2.7000e-01, 1.4800e+00, 4.2800e+00, 9.1000e-01, 3.0000e+00,
         1.0350e+03],
        [1.2250e+01, 4.7200e+00, 2.5400e+00, 2.1000e+01, 8.9000e+01, 1.3800e+00,
         4.7000e-01, 5.3000e-01, 8.0000e-01, 3.8500e+00, 7.5000e-01, 1.2700e+00,
         7.2000e+02],
        [1.3900e+01, 1.6800e+00, 2.1200e+00, 1.6000e+01, 1.0100e+02, 3.1000e+00,
         3.3900e+00, 2.1000e-01, 2.1400e+00, 6.1000e+00, 9.1000e-01, 3.3300e+00,
         9.8500e+02],
        [1.3500e+01, 3.1200e+00, 2.6200e+00, 2.4000e+01, 1.2300e+02, 1.4000e+00,
         1.5700e+00, 2.2000e-01, 1.2500e+00, 8.6000e+00, 5.9000e-01, 1.3000e+00,
         5.0000e+02],
        [1.3760e+01, 1.5300e+00, 2.7000e+00, 1.9500e+01, 1.3200e+02, 2.9500e+00,
         2.7400e+00, 5.0000e-01, 1.3500e+00, 5.4000e+00, 1.2500e+00, 3.0000e+00,
         1.2350e+03]]) : tensor([1., 3., 1., 3., 1.])
1 : tensor([[1.1840e+01, 8.9000e-01, 2.5800e

In [25]:
n_batches=len(final_data)

In [26]:
n_samples=final_data.dataset.samples

In [29]:
n_samples,n_batches,final_data.batch_size

(178, 36, 5)

In [34]:
n_epochs=10


In [37]:
for epochs in range(n_epochs):
    for i,(x,y) in enumerate(final_data):

        ### forward
        ### backward 
        ### update params

        print(f"epoch {epochs}/{n_epochs} : batch {i+1}/{len(final_data)} : shape {x.shape}")

epoch 0/10 : batch 1/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 2/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 3/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 4/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 5/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 6/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 7/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 8/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 9/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 10/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 11/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 12/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 13/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 14/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 15/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 16/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 17/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 18/36 : shape torch.Size([5, 13])
epoch 0/10 : batch 19/36 : shape torch.Size([5, 13])
ep

In [93]:
type(torch.tensor(1))==torch.Tensor

True

### transform 
- a methods which modifies the data so that a model can be trained after trnasformation 

In [94]:
class ToTensor:
    def __call__(self,sample):
        x,y=sample
        if type(x) is not torch.Tensor :
            return torch.from_numpy(x),torch.from_numpy(y)
        else :
            return sample


In [97]:
class Wine_Data_transform(Dataset):

    def __init__(self,path,transform=None):
        ## to read data 
        self.data=np.loadtxt(path,delimiter=',',dtype=np.float32,skiprows=1)
        self.transform=transform
        self.x=self.data[:,1:]
        self.y=self.data[:,0]
        if self.transform is not None:
            self.x,self.y=self.transform((self.x,self.y))

        self.samples=self.x.shape[0]
        self.features=self.x.shape[1]
    
    def __getitem__(self,index):
        ## to get the object at the index present 
        sample = self.x[index],self.y[index]
        if self.transform is not None:
            return self.transform(sample)
        return sample
    def __len__(self):
        return self.samples
    

In [98]:
wine_data=Wine_Data_transform(wine_path,transform=ToTensor())